[colors.normal]
black = "0x2e3436"
red = "0xcc0000"
green = "0x4e9a06"
yellow = "0xc4a000"
blue = "0x3465a4"
magenta = "0x75507b"
cyan = "0x06989a"
white = "0xd3d7cf"

[colors.bright]
black = "0x555753"
red = "0xef2929"
green = "0x8ae234"
yellow = "0xfce94f"
blue = "0x729fcf"
magenta = "0xad7fa8"
cyan = "0x34e2e2"
white = "0xeeeeec"

[colors.primary]
background = "0x272727"
foreground = "0xd3d7cf"

[font]
size = 12.6

[font.normal]
family = "ComicMono Nerd Font"
style = "regular"

[[keyboard.bindings]]
action = "ResetFontSize"
mods = "Control"
key = "Equals"

[[keyboard.bindings]]
action = "IncreaseFontSize"
mods = "Control | Shift"
key = "Plus"

[[keyboard.bindings]]
action = "DecreaseFontSize"
mods = "Control | Shift"
key = "Minus"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
