conf_dir=$$HOME/.config/git

install:
	@mkdir -p $(conf_dir)
	@ln -s -i $$PWD/gitconfig $(conf_dir)/config
	@ln -s -i $$PWD/gitconfig-work $(conf_dir)/config-work
	@ln -s -i $$PWD/gitignore $(conf_dir)/ignore
