#!/bin/bash
# Dense Roach, as in Git Crawler (yes, I know)
#
function get_infos {
    status=$(git -C "$1" status)
    porcelain_status=$(git -C "$1" status --porcelain=1)
    flag=false
    grep -q ahead <<< "$status" && ahead="AHEAD" && flag=true
    grep -q behind <<< "$status" && behind="BEHIND" && flag=true
    untracked=$(grep -c '^??' <<< "$porcelain_status")
    unstaged=$(grep -c '^ .\|^MM' <<< "$porcelain_status")
    staged=$(grep -c '^. \|^MM' <<< "$porcelain_status")
    if [[ $((untracked + unstaged + staged)) -gt 0 ]]; then
        flag=true
    fi
    if $flag; then
        echo "$1: $ahead $behind $staged $unstaged $untracked"
    fi
    
}
export -f get_infos

function check_dir {
    root=$(git -C "$1" rev-parse --show-toplevel 2>/dev/null | xargs basename 2>/dev/null)
    if [[ -n "$root" ]] && [[ "$root" == "$1" ]]; then
        get_infos "$1"
        return 0
    else
        return 1
    fi
}
export -f check_dir


#find * -type d -not -exec bash -c 'check_dir {}' ';' -prune -o -type d -exec bash -c 'get_infos {}' ';'
find * -type d -not -exec bash -c 'check_dir {}' ';' -prune
