#!/bin/bash

while getopts "h" opt; do
	case $opt in
		h) 	echo "Prints bash (readline) keybinds."
			exit 0;;
	esac
done
shift $((OPTIND -1)) 

echo "
MOVEMENT:
C-a: Move to start of line@C-e: Move to end of line
C-f: Move forward a char@C-b: Move backward a char
A-f: Move forward a word@A-b: Move backward a word
C-xx: Moves between cursor and start of line
EDITION:
A-u: Capitalizes from cursor to end of word@A-l: Uncapitalizes from cursor to end of word
A-c: Capitalizes current character, moves to end of word
C-k: Cuts from cursor to end of line@C-k: Cuts from cursor to beginning of line
C-w: Cuts previous word
C-y: Pastes previously cut text@A-y: Cycles through cutting buffer
C-d: Delete current character@C-_: Undo
M-C-H: Backward kill word
PROCESSES:
C-c: Sends SIGINT to current process@C-z: Sends SIGTSTP to current process
C-d: Sends EOF marker to bash
DISPLAY:
C-s: Stops all output@C-q: Resumes all output
C-l: Clears the screen
HISTORY:
C-p: Go up in command history@C-n: Go down in command history
A-r: Reverts change made to this history entry
C-r: Attempts autocompletion from history@C-o: Run autocompleted command
C-g: Aborts autocompletion attempt" \
    | perl -pe 's/(^|@)(.*?):(?!$)/\1\e[1;33m\2\e[m:/g;'\
            -e 's/(^.*:$)/\e[1;4m\1\e[0m/' \
    | column -s"@" -t
#1;4m
#1;33m
