#!/bin/bash
# Setups the bash/zsh session
# Is re-sourced on `Reload`
source variables.sh
source aliases.sh
source init_func
source LESS_TERMCAP # less's config file
source ls_colors
source nnn_config
source bashline_colors

PROMPT_COMMAND="source q_bashline; share_hist"
