gui:
  border: double
git:
  overrideGpg: true # Makes it so signing your commits doesn't make you want to jump off the roof
  branchLogCmd: git denselog {{branchName}}
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  log:
    showGraph: when-maximised
