install:
	@mkdir -p $(conf_base)/i3
	@mkdir -p $(conf_base)/dunst
	@ln -s -$(clobber) $$PWD/i3_config $(conf_base)/i3/config
	@ln -s -$(clobber) $$PWD/dunstrc $(conf_base)/dunst/dunstrc
	@ln -s -$(clobber) $$PWD/picom.conf $(conf_base)/picom.conf
	@ln -s -$(clobber) $$PWD/tpicom.sh $(conf_base)/tpicom
