.SILENT .IGNORE build:
	ln -Ts -$(clobber) $$PWD/env_vars.sh $(bash_setup_dir)/006_env_vars.sh
	ln -Ts -$(clobber) $$PWD/functions.sh $(bash_setup_dir)/007_functions.sh
	ln -Ts -$(clobber) $$PWD/fzf_preview.bash $(bin_dir)/fzf_preview.bash
