#!/bin/python
import subprocess
from functools import reduce
import sys

tmux_vars=[
    "active_window_index",
    "alternate_on",
    "alternate_saved_x",
    "alternate_saved_y",
    "buffer_created",
    "buffer_name",
    "buffer_sample",
    "buffer_size",
    "client_activity",
    "client_cell_height",
    "client_cell_width",
    "client_control_mode",
    "client_created",
    "client_discarded",
    "client_flags",
    "client_height",
    "client_key_table",
    "client_last_session",
    "CLient_name",
    "client_pid",
    "client_prefix",
    "client_readonly",
    "client_session",
    "client_termfeatures",
    "client_termname",
    "client_termtype",
    "client_tty",
    "client_uid",
    "client_user",
    "client_utf8",
    "client_width",
    "client_written",
    "command",
    "command_list_alias",
    "command_list_name",
    "command_list_usage",
    "config_files",
    "copy_cursor_line",
    "copy_cursor_word",
    "copy_cursor_x",
    "copy_cursor_y",
    "current_file",
    "cursor_character",
    "cursor_flag",
    "cursor_x",
    "cursor_y",
    "history_bytes",
    "history_limit",
    "history_size",
    "hook",
    "hook_client",
    "hook_pane",
    "hook_session",
    "hook_session_name",
    "hook_window",
    "hook_window_name",
    "host",
    "host_short",
    "insert_flag",
    "keypad_cursor_flag",
    "keypad_flag",
    "last_window_index",
    "line",
    "mouse_all_flag",
    "mouse_any_flag",
    "mouse_button_flag",
    "mouse_line",
    "mouse_sgr_flag",
    "mouse_standard_flag",
    "mouse_utf8_flag",
    "mouse_word",
    "mouse_x",
    "mouse_y",
    "next_session_id",
    "origin_flag",
    "pane_active",
    "pane_at_bottom",
    "pane_at_left",
    "pane_at_right",
    "pane_at_top",
    "pane_bg",
    "pane_bottom",
    "pane_current_command",
    "pane_current_path",
    "pane_dead",
    "pane_dead_signal",
    "pane_dead_status",
    "pane_dead_time",
    "pane_fg",
    "pane_format",
    "pane_height",
    "pane_id",
    "pane_in_mode",
    "pane_index",
    "pane_input_off",
    "pane_last",
    "pane_left",
    "pane_marked",
    "pane_marked_set",
    "pane_mode",
    "pane_path",
    "pane_pid",
    "pane_pipe",
    "pane_right",
    "pane_search_string",
    "pane_start_command",
    "pane_start_path",
    "pane_synchronized",
    "pane_tabs",
    "pane_title",
    "pane_top",
    "pane_tty",
    "pane_width",
    "pid",
    "rectangle_toggle",
    "scroll_position",
    "scroll_region_lower",
    "scroll_region_upper",
    "search_match",
    "search_present",
    "selection_active",
    "selection_end_x",
    "selection_end_y",
    "selection_present",
    "selection_start_x",
    "selection_start_y",
    "session_activity",
    "session_alerts",
    "session_attached",
    "session_attached_list",
    "session_created",
    "session_format",
    "session_group",
    "session_group_attached",
    "session_group_attached_list",
    "session_group_list",
    "session_group_many_attached",
    "session_group_size",
    "session_grouped",
    "session_id",
    "session_last_attached",
    "session_many_attached",
    "session_marked",
    "session_name",
    "session_path",
    "session_stack",
    "session_windows",
    "socket_path",
    "start_time",
    "uid",
    "user",
    "version",
    "window_active",
    "window_active_clients",
    "window_active_clients_list",
    "window_active_sessions",
    "window_active_sessions_list",
    "window_activity",
    "window_activity_flag",
    "window_bell_flag",
    "window_bigger",
    "window_cell_height",
    "window_cell_width",
    "window_end_flag",
    "window_flags",
    "window_format",
    "window_height",
    "window_id",
    "window_index",
    "window_last_flag",
    "window_layout",
    "window_linked",
    "window_linked_sessions",
    "window_linked_sessions_list",
    "window_marked_flag",
    "window_name",
    "window_offset_x",
    "window_offset_y",
    "window_panes",
    "window_raw_flags",
    "window_silence_flag",
    "window_stack_index",
    "window_start_flag",
    "window_visible_layout",
    "window_width",
    "window_zoomed_flag",
    "wrap_flag",
]

desc=[
    'Index of active window in session',
    "1 if pane is in alternate screen",
    "Saved cursor X in alternate screen",
    "Saved cursor Y in alternate screen",
    "Time buffer created",
    "Name of buffer",
    "Sample of start of buffer",
    "Size of the specified buffer in bytes",
    "Time client last had activity",
    "Height of each client cell in pixels",
    "Width of each client cell in pixels",
    "1 if client is in control mode",
    "Time client created",
    "Bytes discarded when client behind",
    "List of client flags",
    "Height of client",
    "Current key table",
    "Name of the client\'s last session",
    "Name of client",
    "PID of client process",
    "1 if prefix key has been pressed",
    "1 if client is read-only",
    "Name of the client\'s session",
    "Terminal features of client, if any",
    "Terminal name of client",
    "Terminal type of client, if available",
    "Pseudo terminal of client",
    "UID of client process",
    "User of client process",
    "1 if client supports UTF-8",
    "Width of client",
    "Bytes written to client",
    "Name of command in use, if any",
    "Command alias if listing commands",
    "Command name if listing commands",
    "Command usage if listing commands",
    "List of configuration files loaded",
    "Line the cursor is on in copy mode",
    "Word under cursor in copy mode",
    "Cursor X position in copy mode",
    "Cursor Y position in copy mode",
    "Current configuration file",
    "Character at cursor in pane",
    "Pane cursor flag",
    "Cursor X position in pane",
    "Cursor Y position in pane",
    "Number of bytes in window history",
    "Maximum window history lines",
    "Size of history in lines",
    "Name of running hook, if any",
    "Name of client where hook was run, if any",
    "ID of pane where hook was run, if any",
    "ID of session where hook was run, if any",
    "Name of session where hook was run, if any",
    "ID of window where hook was run, if any",
    "Name of window where hook was run, if any",
    "Hostname of local host",
    "Hostname of local host \(no domain name\)",
    "Pane insert flag",
    "Pane keypad cursor flag",
    "Pane keypad flag",
    "Index of last window in session",
    "Line number in the list",
    "Pane mouse all flag",
    "Pane mouse any flag",
    "Pane mouse button flag",
    "Line under mouse, if any",
    "Pane mouse SGR flag",
    "Pane mouse standard flag",
    "Pane mouse UTF-8 flag",
    "Word under mouse, if any",
    "Mouse X position, if any",
    "Mouse Y position, if any",
    "Unique session ID for next new session",
    "Pane origin flag",
    "1 if active pane",
    "1 if pane is at the bottom of window",
    "1 if pane is at the left of window",
    "1 if pane is at the right of window",
    "1 if pane is at the top of window",
    "Pane background colour",
    "Bottom of pane",
    "Current command if available",
    "Current path if available",
    "1 if pane is dead",
    "Exit signal of process in dead pane",
    "Exit status of process in dead pane",
    "Exit time of process in dead pane",
    "Pane foreground colour",
    "1 if format is for a pane",
    "Height of pane",
    "Unique pane ID",
    "1 if pane is in a mode",
    "Index of pane",
    "1 if input to pane is disabled",
    "1 if last pane",
    "Left of pane",
    "1 if this is the marked pane",
    "1 if a marked pane is set",
    "Name of pane mode, if any",
    "Path of pane \(can be set by application\)",
    "PID of first process in pane",
    "1 if pane is being piped",
    "Right of pane",
    "Last search string in copy mode",
    "Command pane started with",
    "Path pane started with",
    "1 if pane is synchronized",
    "Pane tab positions",
    "Title of pane \(can be set by application\)",
    "Top of pane",
    "Pseudo terminal of pane",
    "Width of pane",
    "Server PID",
    "1 if rectangle selection is activated",
    "Scroll position in copy mode",
    "Bottom of scroll region in pane",
    "Top of scroll region in pane",
    "Search match if any",
    "1 if search started in copy mode",
    "1 if selection started and changes with the cursor in copy mode",
    "X position of the end of the selection",
    "Y position of the end of the selection",
    "1 if selection started in copy mode",
    "X position of the start of the selection",
    "Y position of the start of the selection",
    "Time of session last activity",
    "List of window indexes with alerts",
    "Number of clients session is attached to",
    "List of clients session is attached to",
    "Time session created",
    "1 if format is for a session",
    "Name of session group",
    "Number of clients sessions in group are attached to",
    "List of clients sessions in group are attached to",
    "List of sessions in group",
    "1 if multiple clients attached to sessions in group",
    "Size of session group",
    "1 if session in a group",
    "Unique session ID",
    "Time session last attached",
    "1 if multiple clients attached",
    "1 if this session contains the marked pane",
    "Name of session",
    "Working directory of session",
    "Window indexes in most recent order",
    "Number of windows in session",
    "Server socket path",
    "Server start time",
    "Server UID",
    "Server user",
    "Server version",
    "1 if window active",
    "Number of clients viewing this window",
    "List of clients viewing this window",
    "Number of sessions on which this window is active",
    "List of sessions on which this window is active",
    "Time of window last activity",
    "1 if window has activity",
    "1 if window has bell",
    "1 if window is larger than client",
    "Height of each cell in pixels",
    "Width of each cell in pixels",
    "1 if window has the highest index",
    "Window flags with # escaped as ##",
    "1 if format is for a window",
    "Height of window",
    "Unique window ID",
    "Index of window",
    "1 if window is the last used",
    "Window layout description, ignoring zoomed window panes",
    "1 if window is linked across sessions",
    "Number of sessions this window is linked to",
    "List of sessions this window is linked to",
    "1 if window contains the marked pane",
    "Name of window",
    "X offset into window if larger than client",
    "Y offset into window if larger than client",
    "Number of panes in window",
    "Window flags with nothing escaped",
    "1 if window has silence alert",
    "Index in session most recent stack",
    "1 if window has the lowest index",
    "Window layout description, respecting zoomed window panes",
    "Width of window",
    "1 if window is zoomed",
    "Pane wrap flag",
]

tmux_format = "#{{{}}}".format('}@@@@@#{'.join(tmux_vars))
res = subprocess.run(['tmux', 'display', '-p', tmux_format], text=True, capture_output=True).stdout[:-1]
tmux_var_vals = res.split('@@@@@')

CONCISE=True
TABBED=True

max_arg_len = len(reduce(lambda x,y: x if len(x) > len(y) else y, tmux_vars))

for i in range(len(tmux_vars)): 
    print(f"\x1b[1m{tmux_vars[i]}\x1b[m: ", end="")
    if TABBED:
        print(" " * (max_arg_len - len(tmux_vars[i])), end="")
        pass
    if not CONCISE:
        print(f"{desc[i]}\n\t", end="")
    print(f"\x1b[96m{tmux_var_vals[i]}\x1b[m")

print(max_arg_len)
