.SILENT .IGNORE build:
	ln -Ts -$(clobber) $$PWD/aliases.sh $(bash_setup_dir)/001_aliases.sh
	ln -Ts -$(clobber) $$PWD/init_func.sh $(bash_setup_dir)/002_init_func.sh
	ln -Ts -$(clobber) $$PWD/options.bash $(bash_setup_dir)/003_options.bash
	ln -Ts -$(clobber) $$PWD/setup_prompt.sh $(bash_setup_dir)/004_setup_prompt.sh
	ln -Ts -$(clobber) $$PWD/variables.sh $(bash_setup_dir)/005_variables.sh
	ln -Ts -$(clobber) $$PWD/misc_complete.bash $(bash_setup_dir)/500_misc_complete.bash
	ln -Ts -$(clobber) $$PWD/bashrc.sh $$HOME/.bashrc
