build:
	@ln -s -i $$PWD/aliases.sh $(bash_setup_dir)/001_aliases.sh
	@ln -s -i $$PWD/init_func.sh $(bash_setup_dir)/002_init_func.sh
	@ln -s -i $$PWD/options.bash $(bash_setup_dir)/003_options.bash
	@ln -s -i $$PWD/setup_prompt.sh $(bash_setup_dir)/004_setup_prompt.sh
	@ln -s -i $$PWD/variables.sh $(bash_setup_dir)/005_variables.sh
	@ln -s -i $$PWD/profile.sh $$HOME/.profile
	@ln -s -i $$PWD/bashrc.sh $$HOME/.bashrc
